image: alpine:latest

stages:
  - build
  - test
  - integration-testing
  - qa-testing
  - qa-update
  - deploy
  - qa-deploy
  - review
  #- dast
  - staging
  - staging-testing
  - staging-update
  - staging-deploy
  #- canary
  - release
  - production
  #- performance
  - cleanup

variables:
  QA_CONTAINER_NAME: "amblema_front_qa"
  STAGING_CONTAINER_NAME: "amblema_front_staging"

  # Path to QA
  PATH_FOLDER_QA: /home/amblema/amblema-front/qa
  PATH_PROJECT_QA: $PATH_FOLDER_QA/amblema-front

  # Path to staging
  PATH_FOLDER_STAGING: /home/amblema/amblema-front/staging
  PATH_PROJECT_STAGING: $PATH_FOLDER_STAGING

  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  # KUBE_INGRESS_BASE_DOMAIN: domain.example.com

  POSTGRES_USER: user
  POSTGRES_PASSWORD: testing-password
  POSTGRES_ENABLED: "true"
  POSTGRES_DB: $CI_ENVIRONMENT_SLUG

  DOCKER_DRIVER: overlay2

  ROLLOUT_RESOURCE_TYPE: deployment

  DOCKER_TLS_CERTDIR: "" # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

# Jobs for Staging environment
.teststagingscript: &test
  script:
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - if [ -z "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" ]; then
    - git pull $CI_REPOSITORY_URL $CI_COMMIT_REF_NAME
    - else
    - git pull $CI_REPOSITORY_URL $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - fi
    - npm install
    - npm rebuild
    - npm run test

staging-auto-tests:
  stage: staging-testing
  image: devbinaural/nginx-angular:latest
  tags:
    - amblema-test
  <<: *test
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

staging-update:
  stage: staging-update
  script:
    - if ! [ -d $PATH_PROJECT_STAGING ]; then
    - mkdir -p $PATH_PROJECT_STAGING
    - cd $PATH_PROJECT_STAGING
    - git clone -b master --single-branch $CI_REPOSITORY_URL .
    - else
    - cd $PATH_PROJECT_STAGING
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git stash drop || echo "Nothing to drop in stash"
    - git add .
    - git stash
    - git pull $CI_REPOSITORY_URL master
    - fi
  tags:
    - amblema
  only:
    - master

staging-run-tests:
  stage: staging-deploy
  tags:
    - amblema-front
  script:
    - cd $PATH_PROJECT_STAGING
    - docker-compose -f docker-compose.staging.yml -p $STAGING_CONTAINER_NAME exec -T web /bin/bash -c "cd /home/amblema && npm run test"
  only:
    - master
  when: manual

staging-deploy:
  stage: staging-deploy
  script:
    - cd $PATH_PROJECT_STAGING
    # - if ! docker ps --format '{{.Names}}' | grep -w $STAGING_CONTAINER_NAME &> /dev/null; then
    - docker-compose -f docker-compose.staging.yml -p $STAGING_CONTAINER_NAME up -d
    - docker-compose -f docker-compose.staging.yml -p $STAGING_CONTAINER_NAME restart
    - docker-compose -f docker-compose.staging.yml -p $STAGING_CONTAINER_NAME exec -T web /bin/bash -c "cd /home/amblema && npm install"
    - docker-compose -f docker-compose.staging.yml -p $STAGING_CONTAINER_NAME exec -T web /bin/bash -c "cd /home/amblema && npm run build"
    - docker-compose -f docker-compose.staging.yml -p $STAGING_CONTAINER_NAME exec -T web /bin/bash -c "cd /home/amblema && npm run build:ssr"
    - docker-compose -f docker-compose.staging.yml -p $STAGING_CONTAINER_NAME exec -T web /bin/bash -c "cd /home/amblema && npm run serve:ssr &"
  tags:
    - amblema
  only:
    - master

staging-turn-off:
  stage: staging-deploy
  script:
    - cd $PATH_PROJECT_STAGING
    - rm -rf dist/
  tags:
    - amblema
  only:
    - master
  when: manual

include:
  - project: binaural/ecosistema/DevOps/ci-cd/ymls
    file: /semantic-versioning/release.gitlab-ci.yml #para versionado
