#USO-LOCAL - Use command docker-compose -f docker-compose.dev.yml up to set this specific .yml and up the docker-compose
version: "3.3"

services:
  angular8local:
    image: devbinaural/angular:8.0.0
    container_name: angular_amblema
    networks:
      - db_network
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: bash -c "npm install && ng serve --host 0.0.0.0"
    ports:
      - "22222:4200"
      - "22223:4000"

networks:
  db_network:
    external:
      name: amblered
