<<<<<<< HEAD
#USO-PROD -Use command docker-compose up -d
=======
#USO-LOCAL - Use command docker-compose -f docker-compose.dev.yml up to set this specific .yml and up the docker-compose
>>>>>>> 34e77dfdfa04b886a7ca575eed70e06996c4a276
version: "3.5"

services:
  angular8local:
    image: devbinaural/angular:8.0.0
    container_name: angular_amblema
    volumes:
      - ".:/app"
      - "/app/node_modules"
    # command: bash -c "npm install && ng serve --host 0.0.0.0"
    command: bash -c "npm install -g && npm install && ng serve --host 0.0.0.0"
    ports:
<<<<<<< HEAD
      - 9014:80
      - 4200:4200
    env_file:
      # Look example on .env.example
      - .env
    volumes:
      - .:/home/amblema
    command: >
      /bin/bash -c "envsubst '$$NGINX_HOST$$NGINX_PORT$$NGINX_ROOT$$SSR_HOST$$SSR_PORT' < /home/amblema/vhost-template.conf > /etc/nginx/conf.d/default.conf && envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html && exec nginx -g 'daemon off;'"
    networks:
      - default
networks:
  default:
    external:
      name: amblema_db_db_network
=======
      - "22222:4200"
      - "22223:4000"
    environment:
      - CHOKIDAR_USEPOLLING=true
>>>>>>> 34e77dfdfa04b886a7ca575eed70e06996c4a276
