version: '3.5'
services:
  web:
    container_name: amblema_web
    image: devbinaural/nginx-angular:latest
    tty: true
    ports:
      - 9014:80
      - 4200:4200
    env_file:
      - .env
    # environment:
      # Set enviroment values in .env file or here
      # - NGINX_HOST=
      # - NGINX_PORT=
      # - NGINX_ROOT=
    volumes:
      - amblema_web:/home/amblema
    command: >
      /bin/bash -c "envsubst < /home/amblema/vhost-template.conf > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
    networks:
      - default
volumes:
  amblema_web:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
networks:
  default:
    driver: bridge
    name: amblema_web_network
