#USO-PROD -Use command docker-compose up -d
version: "3.5"
services:
  support:
    container_name: amblema-front-support
    image: devbinaural/nginx-angular:latest
    tty: true
    ports:
      - 10514:10514
    volumes:
      - ${PWD}:/home/amblema
    networks:
      - default
  web:
    container_name: amblema_web
    image: devbinaural/nginx-angular:latest
    tty: true
    ports:
      - 9014:80
      - 4200:4200
    env_file:
      # Look example on .env.example
      - .env
    volumes:
      - .:/home/amblema
    command: >
      /bin/bash -c "envsubst '$$NGINX_HOST$$NGINX_PORT$$NGINX_ROOT$$SSR_HOST$$SSR_PORT' < /home/amblema/vhost-template.conf > /etc/nginx/conf.d/default.conf && envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html && exec nginx -g 'daemon off;'"
    networks:
      - default
networks:
  default:
    external:
      name: amblema_db_db_network
