#USO-LOCAL - Use command docker-compose -f docker-compose.staging.yml up to set this specific .yml and up the docker-compose
version: "3.5"
services:
  web:
    container_name: amblema_front_staging
    image: devbinaural/nginx-angular:latest
    tty: true
    working_dir: "/home/amblema"
    ports:
      - $OUT_PORT:80
    env_file:
      - .env
    volumes:
      - ./:/home/amblema
      - ./vhost-template.conf:/etc/nginx/conf.d/default.conf
    command: >
      /bin/bash -c "npm install && npm run build && envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html && exec nginx -g 'daemon off;'"
