#USO-LOCAL - Use command docker-compose up -d || npm start
version: "3.5"

services:
  angular:
    image: devbinaural/angular:8.0.0
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: bash -c "npm install -g && npm install && ng serve --host 0.0.0.0"
    ports:
      - "22222:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
