# #USO-LOCAL - Use command docker-compose -f docker-compose.dev.yml up to set this specific .yml and up the docker-compose
# version: "3.5"

# services:
#   angular8local:
#     image: devbinaural/angular:8.0.0
#     container_name: angular_amblema
#     volumes:
#       - ".:/app"
#       - "/app/node_modules"
#     # command: bash -c "npm install && ng serve --host 0.0.0.0"
#     command: bash -c "npm install -g && npm install && ng serve --host 0.0.0.0"
#     ports:
#       - $OUT_PORT:4200
#     environment:
#       - CHOKIDAR_USEPOLLING=true

#Serve prod
version: "3.5"
services:
  host-optimized-service:
    container_name: amblema_front
    image: devbinaural/nginx-angular:latest
    tty: true
    working_dir: "/home/amblema"
    ports:
      - $OUT_PORT:80
    env_file:
      - .env.prod
    volumes:
      - ./:/home/amblema
      - ./vhost-template.conf:/etc/nginx/conf.d/default.conf
    command: >
      /bin/bash -c "envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html && exec nginx -g 'daemon off;'"
