version: '3.5'
services:
  web:
    container_name: amblema_front_qa
    image: devbinaural/nginx-angular:latest
    tty: true
    ports:
      - 10510:80
      - 10511:4200
    env_file:
      - .env
    # environment:
      # Set enviroment values in .env file or here
      # - NGINX_HOST=
      # - NGINX_PORT=
      # - NGINX_ROOT=
      # - SSR_PORT=
    volumes:
      - amblema_front_qa:/home/amblema
    command: >
      /bin/bash -c "envsubst '$$NGINX_HOST$$NGINX_PORT$$NGINX_ROOT$$SSR_PORT' < /home/amblema/vhost-template.conf > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
    networks:
      - default
volumes:
  amblema_front_qa:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
networks:
  default:
    driver: bridge
    name: amblema_front_network
