version: "3.5"
services:

  support:
    container_name: amblema-front-support
    image: devbinaural/nginx-angular:latest
    tty: true
    ports:
      - 10514:10514
    volumes:
      - ${PWD}:/home/amblema
    networks:
      - default

  web:
    container_name: amblema_front_staging
    image: devbinaural/nginx-angular:latest
    tty: true
    ports:
      - 10512:80
      - 10513:4200
    env_file:
      - .env.staging
    # environment:
    # Set enviroment values in .env.staging file or here
    # - NGINX_HOST=
    # - NGINX_PORT=
    # - NGINX_ROOT=
    # - SSR_HOST=
    # - SSR_PORT=
    # - G_MAPS_ID=
    # - G_ANALYTICS_ID=
    volumes:
      - amblema_front_staging:/home/amblema
    command: >
      /bin/bash -c "envsubst '$$NGINX_HOST$$NGINX_PORT$$NGINX_ROOT$$SSR_HOST$$SSR_PORT' < /home/amblema/vhost-template.conf > /etc/nginx/conf.d/default.conf
      && envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html
      && exec nginx -g 'daemon off;'"
    networks:
      - default
volumes:
  amblema_front_staging:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
networks:
  # default:
  #   driver: bridge
  #   name: amblema_front_network
  default:
    external:
      name: amblema_db_network
