#USO-LOCAL - Use command docker-compose -f docker-compose.dev.yml up -d to set this specific .yml and up the docker-compose || npm start
version: "3.3"

services:
  angular:
    image: devbinaural/angular:8.0.0
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: bash -c "npm install -g && npm install && ng serve --host 0.0.0.0"
    ports:
      - "22222:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
