# To serve Bundle with nginx
version: "3.5"
services:
  host-optimized-service:
    container_name: $CONTAINER_NAME
    image: devbinaural/nginx-angular:latest
    restart: always
    tty: true
    working_dir: "/home/amblema"
    ports:
      - $OUT_PORT:80
    env_file:
      - .env

    volumes:
      - ./:/home/amblema
      - ./vhost-template.conf:/etc/nginx/conf.d/default.conf
    # command: >
    #   /bin/bash -c "envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html && exec nginx -g 'daemon off;'"
    command: >
      /bin/bash -c "exec nginx -g 'daemon off;'"
