<<<<<<< HEAD
#USO-STAGING - Use command docker-compose -f docker-compose.staging.yml up to set this specific .yml and up the docker-compose
=======
#USO-LOCAL - Use command npm i && npm run build && docker-compose -f docker-compose.staging.yml up to set this specific .yml and up the docker-compose
>>>>>>> 34e77dfdfa04b886a7ca575eed70e06996c4a276
version: "3.5"
services:
  host-optimized-service:
    container_name: amblema_front_staging
    image: devbinaural/nginx-angular:latest
    tty: true
    working_dir: "/home/amblema"
    ports:
      - $OUT_PORT:80
    env_file:
      - .env
    volumes:
      - ./:/home/amblema
      - ./vhost-template.conf:/etc/nginx/conf.d/default.conf
    command: >
<<<<<<< HEAD
      /bin/bash -c "npm install && npm run build && envsubst '$$NGINX_HOST$$NGINX_PORT$$NGINX_ROOT$$SSR_HOST$$SSR_PORT' < /home/amblema/vhost-template.conf > /etc/nginx/conf.d/default.conf && envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html && exec nginx -g 'daemon off;'"
    networks:
      - default
volumes:
  amblema_front_staging:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
networks:
  default:
    external:
      name: amblema_db_network
=======
      /bin/bash -c "envsubst '$$G_MAPS_ID$$G_ANALYTICS_ID' < /home/amblema/src/index.template.html > /home/amblema/src/index.html && exec nginx -g 'daemon off;'"
>>>>>>> 34e77dfdfa04b886a7ca575eed70e06996c4a276
