import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-steps',
  templateUrl: './steps.component.html',
  styleUrls: ['./steps.component.scss']
})
export class StepsComponent implements OnInit {
  generalSteps = [
    {
      name: 'Encontrar una escuela',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Encontrar un padrino',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Encontrar un coordinador',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Planificacion del taller inicial',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: {
        url: 'https://youtu.be/FldLWuBibuw',
        name: 'Google',
      },
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Confirmacion de AmbLeMa',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
  ];
  sponsorSteps = [
    {
      name: 'Presentacion a la escuela',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Conoce el metodo AmbLeMa',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: {
        url: 'http://www.africau.edu/images/default/sample.pdf',
        name: 'Agreement name',
      },
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Llenar planilla de escuela',
      status: 'En espera',
      isForm: true,
      type: 1,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Llenar planilla de coordinador',
      status: 'En espera',
      isForm: true,
      type: 2,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Convenio Padrino - Escuela',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: {
        url: 'http://www.africau.edu/images/default/sample.pdf',
        name: 'Agreement name',
      },
      upload: true,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Convenio Escuela - Fundacion',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: {
        url: 'http://www.africau.edu/images/default/sample.pdf',
        name: 'Agreement name',
      },
      upload: true,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
  ];
  coordinatorSteps = [
    {
      name: 'Llenar planilla de escuela',
      status: 'En espera',
      isForm: true,
      type: 3,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Llenar planilla de padrino',
      status: 'En espera',
      isForm: true,
      type: 4,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Enviar curriculum vitae',
      text: null,
      status: 'En espera',
      video: null,
      file: null,
      upload: true,
      send: true,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Completar los modulos de formacion',
      text: null,
      status: 'En espera',
      video: null,
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: true,
      checks: [],
      save: false,
    },
    {
      name: 'Pasos del taller inicial',
      text: null,
      status: 'En espera',
      video: null,
      file: null,
      upload: false,
      send: false,
      isForm: false,
      goMods: false,
      checks: [
        {text: 'Lorem ipsum dolor', checked: true}, {text: 'Lorem ipsum dolor', checked: false},
        {text: 'Lorem ipsum dolor', checked: false}, {text: 'Lorem ipsum dolor', checked: false},
        {text: 'Lorem ipsum dolor', checked: false}, {text: 'Lorem ipsum dolor', checked: false},
        {text: 'Lorem ipsum dolor', checked: false}, {text: 'Lorem ipsum dolor', checked: false},
      ],
      save: true,
    },
  ];
  schoolSteps = [
    {
      name: 'Presentacion al padrino',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: null,
      upload: true,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Llenar planilla de padrino',
      status: 'En espera',
      isForm: true,
      type: 5,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Llenar planilla de coordinador',
      status: 'En espera',
      isForm: true,
      type: 6,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Convenio Padrino - Escuela',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: {
        url: 'http://www.africau.edu/images/default/sample.pdf',
        name: 'Agreement name',
      },
      upload: true,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
    {
      name: 'Convenio Escuela - Fundacion',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      status: 'En espera',
      video: null,
      file: {
        url: 'http://www.africau.edu/images/default/sample.pdf',
        name: 'Agreement name',
      },
      upload: true,
      send: false,
      isForm: false,
      goMods: false,
      checks: [],
      save: false,
    },
  ];

  constructor() { }

  ngOnInit() {
  }

}
