export const mockSchoolSections = [
  {
    sectionName: 'Preescolar, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Jhanier Antonio Blanco',
      'Jhaider Andrés Blanco',
      'Neiver Cabeza',
      'Kerstin Flores',
      'Josué Gamarra',
      'Mathias García',
      'Sara Mendoza',
      'Samira Machado',
      'Gabriela  Molina',
      'Ronald Rodríguez',
      'Marielvis Vegas',
      'Mariangely Betancourt',
      'Nicolee Castillo',
      'Jeandri Guerra',
      'Aarón Granadillo',
      'Ronald  Quintero',
      'Gianna Salcedo',
      'Jeremy Suárez',
      'Enyelber Castillo',
      'Mateo Chacón',
    ],
    sectionGrade: '0',
  },
  {
    sectionName: 'Preescolar, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Leysmar Paredes',
      'Xavier Marcano',
      'Gabriel Martínez',
      'Ezequiel Bohada',
      'Miguel  Rivas',
      'Ricardo Morillo',
      'Aurora Cobi',
      'Jeremías Moncada',
      'Luis  Fajardo',
      'Shaelot Benítez',
      'Enyerbet  Castillo',
      'Katniss Hernández',
      'Carolay Rodríguez',
      'Sophia Hinagas',
      'Manuel Peña',
      'Dereth Rodríguez',
      'Fabián Villamizar',
      'Marlon Mejías',
      'Santiago Márquez',
      'Jeremías Nieves',
      'Valery López',
    ],
    sectionGrade: '0',
  },
  {
    sectionName: '1er Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Jadriel Arcila',
      'Lesbia Camacho',
      'Ashley Flores',
      'Isabella Gallardo',
      'Kevin  Guevara ',
      'Sarah Pérez ',
      'Andrew Pérez ',
      'Luciannys Reina ',
      'Sanny Romero',
      'Mathias Garcias',
      'Samira Mendoza ',
      'Sara Mendoza',
      'Mauricio  Ribero ',
      'Ronald Rodríguez ',
      'Marielvys  Vegas',
      'Jhaider Blanco ',
      'Jhanier Blanco ',
      'Neiver  Cabeza',
      'Kerstin Flores',
      'Dereth Rodríguez ',
    ],
    sectionGrade: '1',
  },
  {
    sectionName: '1er Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Manuel Piña',
      'Ronald Quintero',
      'Gianna  Salcedo',
      'Neives Ceballos',
      'Lucia Narváez',
      'Nahomiz Olivero',
      'Fabian Campo Verde',
      'Hyller Guerra',
      'Jhosep León',
      'Rosmely Ramírez',
      'Jefferson Rojas',
      'Angel Muria',
      'Miller Aular',
      'Franchezca Flores',
      'Aranza Cordero',
      'Ciro Jaramillo',
      'Valentina Bastida',
      'Enyelber Castillo',
      'Jeandri Guerra',
    ],
    sectionGrade: '1',
  },
  {
    sectionName: '2do Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Jose Olivares',
      'Anyelit Roa',
      'Jessimar Mata',
      'Maholis Quintero',
      'Pilar Cabeza',
      'Jeliagnis Valderrama',
      'Alejandro Tovar',
      'Ivanna Prin',
      'Isaac Navarro',
      'Hendrix Bravo',
      'Isaac Almeida',
      'Antony Bastidas ',
      'Ariannilis Gonzalez',
      'Santiago Guiliarte',
      'Sleykysmar Ramírez ',
      'Betzabeth Jiménez ',
      'Jheicob Cohen',
      'Miguel Martínez ',
      'Liliana Mejías ',
      'Angelit Roa',
      'Arlegnis Valderrama',
      'Allen Velázquez ',
      'Giulianna Andrade',
      'Diego Torres',
      'Alan  Correa',
      'Gabriel  Castillo',
      'María  Suárez',
    ],
    sectionGrade: '2',
  },
  {
    sectionName: '2do Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Kleiber Rangel',
      'Delinyer Torres',
      'Gabriel Castillo',
      'Rihanna  Espinoza',
      'Gabriel Gil',
      'Diana Ramírez',
      'Jhoybert Ache',
      'Matías Rosales',
      'Edwin Castillo',
      'Eyan Arvelo',
      'Keinner Osta',
      'Samanta Moron',
      'Gerardo Cuenca',
      'Erick Sabala',
      'Joselin Granadillo',
      'Daniel Parra',
      'Rosibel Sierra',
      'Luis Blanco',
      'Bayolet Mendoza',
    ],
    sectionGrade: '2',
  },
  {
    sectionName: '3er Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Samira Rodríguez ',
      'Nataly Villegas',
      'Deyver  Gutierrez',
      'Jose Lucena ',
      'Stefhany España',
      'Cristopher Rengifo ',
      'Moises  Gamarra',
      'Engery Alvarado',
      'Daikeny Gerber',
      'Milkelis Manaure',
      'Karelys Mulato',
      'Adonis Giron',
      'Sophia Herrada ',
      'Andrea Pulido',
      'Leonardo Sanchez',
      'Naherobis Morillo',
      'Jonaiker Solano',
      'Genesis Osal',
      'Santiago Aliendo',
      'Diego Aliendo',
      'Miguel  Ladera',
      'Esther Mendoza ',
    ],
    sectionGrade: '3',
  },
  {
    sectionName: '3er Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Valeria García',
      'Danny  Mejia',
      'Roimer Reina',
      'Sonnary Herrera',
      'Julianysmar Carrero',
      'Jarvelys Yebsco',
      'Antonhy Damarases',
      'Suhid Cordero',
      'Darkelis Cardozo',
      'Daanubi Guerra',
      'Ashley Valentina Pacheco',
      'Nazareth Ramírez',
      'Jeiner Narvaez',
      'Dixon Ramírez',
      'Eva Colón',
      'Sebastián Bastida',
      'Danexy Izquiel',
      'Samuel Rodríguez',
      'Eskleidy Montesino',
      'Reniel Toledo',
      'Diana Pacheco',
      'Sair Cordero',
    ],
    sectionGrade: '3',
  },
  {
    sectionName: '4to Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Valeria  Abreu',
      'Cristian Acosta ',
      'Mahatma Blanco ',
      'Omar Cabeza',
      'Daylith Campos ',
      'Adrian  Castrillo',
      'Marianyely Cedeño ',
      'Cristberlin Cedeño',
      'Camila Coronado',
      'Karelis Duran',
      'Jose Flores ',
      'Dianneli Gonzalez ',
      'Estefania Gonzalez ',
      'Deivis Gutiérrez ',
      'Yoiber Mendoza ',
      'Albert Muria',
      'Dalysmel Ortiz',
      'Aaron Peralta',
      'Angel  Rivero',
      'Saviel Rodiguez',
      'Yulienny Rodríguez ',
      'Sebastian Suarez',
      'Nicol Zuñiga',
      'Yenis Vargas ',
      'Iriannys Urbina',
      'Marielis Atuñez',
      'Lucely Loaiza',
    ],
    sectionGrade: '4',
  },
  {
    sectionName: '4to Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Luciana Perry',
      'Ariannys Fumero',
      'Ariannys Guerra',
      'Jhoiner Ache',
      'Ezequiel Moncada',
      'Susej Mendez',
      'Mariangel Gómez',
      'Fernando Ramírez',
      'Jiorgelis Rodríguez',
      'Carwin Castillo',
      'Jarelys Sabala',
      'Marianny Jiménez',
      'Diliyer Flores',
      'Rachelle Hernández',
      'Aslhey Ruíz',
      'Abraham Martínez',
      'Harviet Delgado',
      'Kristian Lizarraga',
      'Sebastián Álvarez',
      'Albanis Duran',
      'Dana Ron',
      'Santiago Rosales',
      'Lucely Loviza',
      'José Gutiérrez',
      'Luciana  Perry',
      'Georgelis Avendaño',
      'Fernando Ramírez',
    ],
    sectionGrade: '4',
  },
  {
    sectionName: '5to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Amada  Ramírez',
      'Scarlet Piñango',
      'Cristian Guaregua',
      'Luis  Astor',
      'Valeria Lombardi',
      'Moisés Soto',
      'Esael Ramos',
      'Samuel Romero',
      'Darwinson Belisario',
      'Dixon Pacheco',
      'Sebastian Navas',
      'Erick Salazar',
    ],
    sectionGrade: '5',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
]

const sectionImg =
  'https://amblema.org/resources/images/school_years/5e823371e01964539e0e5f68/pecas/5f86e268c1b730ce9dcae9b6/yearbook/4/60dcdf37df94c5238c833b39.jpeg'

export const mocksPdfData = {
  schoolYear: '2021 - 2022',
  sponsorName: 'Triz y Beto',
  sponsorLogo:
    'https://amblema.org/resources/images/school_years/5e823371e01964539e0e5f68/pecas/5f86e26cc1b730ce9dcae9c0/yearbook/5/6112d46b9db0b0a2c5903c83.jpeg',
  sponsorText:
    '      Queridos niños, maestros, representantes, obreros, directivo y demás miembros de esta gran familia llamada Unidad Educativa Estadal Santa Inés, sentimos un orgullo enorme al verlos crecer cada día, sus avances y sus logros, sin duda, nos llenan el corazón de una gran satisfacción. \n      Queremos decirles, que tenemos la convicción de que cada día se están desarrollando como héroes de nuestro país, y lo mejor de todo, es que cada uno de ustedes crece como persona gracias a los valores y conocimientos, varios, producto de la valiosa labor que ha emprendido Fundación AmbLeMa en nuestra escuela desde hace varios años. \n      De corazón, queremos darles las gracias por hacernos parte de este equipo maravilloso que nos motiva a seguir adelante. También, queremos darles las gracias por demostrarnos que con esfuerzo y perseverancia se pueden lograr todos nuestros sueños. \n      Ustedes son el futuro de nuestra Venezuela. Por eso les invitamos a permanecer en pie aun cuando los obstáculos sean muchos. Estamos convencidos que la semilla que sembramos en ustedes dará frutos que contribuirán en la transformación de nuestro país. \n      Sigamos adelante, trabajando en equipo y creciendo diariamente. \n      Con cariño, Triz & Beto',
  coordinatorName: 'Elisa Rojas',
  coordinatorImg:
    'https://amblema.org/resources/images/school_years/5e823371e01964539e0e5f68/pecas/5ff8a6a20418f4e22ae0465d/yearbook/19/61188d2e0495d926a12b4102.jpeg',
  coordinatorText:
    'Elisa Rojas es Licenciada en Comunicación Social mención Desarrollo Social, egresada de la Universidad Católica Cecilio Acosta (UNICA). Oriunda de Maracay estado Aragua,  llega a la familia AmbLeMa en septiembre de 2018 por invitación del profesor Tomás Linares, tras haberse presentado en una de las escuelas AmbLeMa, con la obra de títeres que ella misma dirige.  \nEn su debut como coordinadora, inicia con dos escuelas, U.E.E. Los Próceres y U.E.E. 24 de Octubre, ambas, ubicadas en Santa Rita,  específicamente en el municipio Linares Alcántara, estado Aragua. Para el siguiente año, se le presenta  un nuevo reto, coordinar la U.E.E. Santa Inés y U.E.E. Armida Morillo, las cuales se encuentran  en La Morita II, del mencionado municipio Aragüeño. \nTras la maravillosa experiencia de Venezuela Megadiversa y pese a los inconvenientes de estudiar desde la distancia, con la Feria Científica AmbLeMa el cual fue asumido con la misma responsabilidad, un nuevo año escolar toca la puerta en pandemia, Bosque de Chocolate. En esta oportunidad, Rojas reconoce los obstáculos y plantea estrategias para afrontarlos logrando la mayor integración de los estudiantes, ya que un grupo está en clases presenciales y otro se mantiene a distancia. \nEn AmbLeMa, somos testigo del crecimiento de los docentes como profesionales y como personas. Los coordinadores de AmbLeMa no somos los mismos que cuando llegamos, eso de debe a que estamos en constante entrenamiento, estamos conscientes de la importancia de crecer diariamente para poder ofrecer  a los docentes novedosas herramientas de trabajo. Hoy por hoy, ha sido maravilloso ver cómo directivo, docentes y representantes, responden a las actividades propuestas con gran entusiasmo, desde cada Hogar AmbLeMa o desde el aula de clases. \nJuntos en nuestra escuela seguimos Haciendo Que Suceda...',
  schoolName: 'Unidad Educativa Estadal Santa Inés - AM',
  schoolImg:
    'https://amblema.org/resources/images/school_years/5e823371e01964539e0e5f68/pecas/5f86e268c1b730ce9dcae9b6/yearbook/8/6108664ce45b72e780f36c54.jpeg',
  schoolText:
    'Nuestra escuela es un lugar agradable y campestre ubicado al final de la comunidad la Pintera, espacio que aunque carece de muchas cosas, brinda un espacio acogedor dónde un grupo de docentes ponen en práctica el verdadero significado del HQS. \n\nEl canto de las aves y la brisa que hace mover las plantas y entra por las ventanas brinda una sensación agradable a quienes visitan el lugar. \n\nDificultades muchas, necesidades muchas, historias conmovedoras muchas, pero desde AmbLeMa les hemos dado ese impulso para entender que es posible una educación de calidad pese a los obstáculos. \n\nLa institución cuenta con una estructura organizativa encabezada por su directora la profesora Anubis Mier y Terán, quien diariamente lucha por el bienestar de su escuela de la mano de 12 educadores, que imparten clases desde preescolar hasta 6to grado, un especialista, una secretaria, un obrero y un bibliotecario.\n\nÉste año, cada docente plantea su propia estrategia de trabajo adaptándose a la semipresencialidad, una realidad que estamos viviendo motivada por la pandemia. Cada quien trabaja a su ritmo y según las condiciones particulares. \n\nLo importante es que se ha hecho el trabajo, nada  les impide  seguir Haciendo que las cosas Sucedan, un reto sólo para los valientes. ',
  schoolCity: 'Maracay',
  historicalReviewName: 'Reseña Histórica',
  historicalReviewText:
    'La historia de la U. E. E. Santa Inés, comienza en septiembre de 2005, cuando el señor Domingo Pinto de Meneses y la señora María de Salazar, concretan la compra del terreno en el sector La Pintera del barrio Santa Inés, ubicado en La Morita II, municipio Linares Alcántara del estado Aragua, con el fin de crear módulos educativos con su respectiva cancha. \nDidalco Bolívar, gobernador de la entidad aragueña para ese entonces, aprueba el proyecto para construcción de un preescolar y un módulo básico tipo A4. A mitad de la construcción, el ingeniero encargado informa que se agota el presupuesto dejando la obra inconclusa. \nLuego de varios años de incesante lucha, la señora María junto al Consejo Comunal del sector realizan algunos arreglos a la obra y se les autoriza la apertura de la institución, que abre sus puertas el 3 de noviembre de 2014 con tres secciones de preescolar, bajo la dirección de la profesora Domaiza Rojas. \nPara el año escolar 2015 - 2016 se apertura 1ro y 2do grado, y cada año se incorporan más grados. Actualmente, la escuela trabaja de preescolar hasta 6to grado en ambos turnos, ya que solo cuenta con seis aulas. Carece de servicio eléctrico y oficina para dirección, cancha deportiva y baño para docentes. \nAmbLeMa llega a la institución por recomendación de la profesora Rosa Bastardo, directora de la U.E.E. 24 de Octubre, escuela con años de trayectoria aplicando la herramienta. Ella, quien es vecina del sector, hizo la solicitud al profesor Tomás Linares para que AmbLeMa llegara a  su comunidad (Santa Inés). Tras concretarse un padrino, se visitó la institución, en aquel primer encuentro con el directivo, se coordinó  el taller inicial para presentar el plan de trabajo al personal y se planteó comenzar en el año escolar 2019/2020. ',
  historicalReviewImg:
    'https://amblema.org/resources/images/school_years/5e823371e01964539e0e5f68/pecas/5f86e268c1b730ce9dcae9b6/yearbook/4/60dcdf37df94c5238c833b39.jpeg',
  schoolSections: [
    {
      sectionName: 'Preescolar, sección: A',
      sectionImg,
      sectionStudents: [
        'Jhanier Antonio Blanco',
        'Jhaider Andrés Blanco',
        'Neiver Cabeza',
        'Kerstin Flores',
        'Josué Gamarra',
        'Mathias García',
        'Sara Mendoza',
        'Samira Machado',
        'Gabriela  Molina',
        'Ronald Rodríguez',
        'Marielvis Vegas',
        'Mariangely Betancourt',
        'Nicolee Castillo',
        'Jeandri Guerra',
        'Aarón Granadillo',
        'Ronald  Quintero',
        'Gianna Salcedo',
        'Jeremy Suárez',
        'Enyelber Castillo',
        'Mateo Chacón',
      ],
      sectionGrade: '0',
    },
    {
      sectionName: 'Preescolar, sección: B',
      sectionImg,
      sectionStudents: [
        'Leysmar Paredes',
        'Xavier Marcano',
        'Gabriel Martínez',
        'Ezequiel Bohada',
        'Miguel  Rivas',
        'Ricardo Morillo',
        'Aurora Cobi',
        'Jeremías Moncada',
        'Luis  Fajardo',
        'Shaelot Benítez',
        'Enyerbet  Castillo',
        'Katniss Hernández',
        'Carolay Rodríguez',
        'Sophia Hinagas',
        'Manuel Peña',
        'Dereth Rodríguez',
        'Fabián Villamizar',
        'Marlon Mejías',
        'Santiago Márquez',
        'Jeremías Nieves',
        'Valery López',
      ],
      sectionGrade: '0',
    },
    {
      sectionName: '1er Grado, sección: A',
      sectionImg,
      sectionStudents: [
        'Jadriel Arcila',
        'Lesbia Camacho',
        'Ashley Flores',
        'Isabella Gallardo',
        'Kevin  Guevara ',
        'Sarah Pérez ',
        'Andrew Pérez ',
        'Luciannys Reina ',
        'Sanny Romero',
        'Mathias Garcias',
        'Samira Mendoza ',
        'Sara Mendoza',
        'Mauricio  Ribero ',
        'Ronald Rodríguez ',
        'Marielvys  Vegas',
        'Jhaider Blanco ',
        'Jhanier Blanco ',
        'Neiver  Cabeza',
        'Kerstin Flores',
        'Dereth Rodríguez ',
      ],
      sectionGrade: '1',
    },
    {
      sectionName: '1er Grado, sección: B',
      sectionImg,
      sectionStudents: [
        'Manuel Piña',
        'Ronald Quintero',
        'Gianna  Salcedo',
        'Neives Ceballos',
        'Lucia Narváez',
        'Nahomiz Olivero',
        'Fabian Campo Verde',
        'Hyller Guerra',
        'Jhosep León',
        'Rosmely Ramírez',
        'Jefferson Rojas',
        'Angel Muria',
        'Miller Aular',
        'Franchezca Flores',
        'Aranza Cordero',
        'Ciro Jaramillo',
        'Valentina Bastida',
        'Enyelber Castillo',
        'Jeandri Guerra',
      ],
      sectionGrade: '1',
    },
    {
      sectionName: '2do Grado, sección: A',
      sectionImg,
      sectionStudents: [
        'Jose Olivares',
        'Anyelit Roa',
        'Jessimar Mata',
        'Maholis Quintero',
        'Pilar Cabeza',
        'Jeliagnis Valderrama',
        'Alejandro Tovar',
        'Ivanna Prin',
        'Isaac Navarro',
        'Hendrix Bravo',
        'Isaac Almeida',
        'Antony Bastidas ',
        'Ariannilis Gonzalez',
        'Santiago Guiliarte',
        'Sleykysmar Ramírez ',
        'Betzabeth Jiménez ',
        'Jheicob Cohen',
        'Miguel Martínez ',
        'Liliana Mejías ',
        'Angelit Roa',
        'Arlegnis Valderrama',
        'Allen Velázquez ',
        'Giulianna Andrade',
        'Diego Torres',
        'Alan  Correa',
        'Gabriel  Castillo',
        'María  Suárez',
      ],
      sectionGrade: '2',
    },
    {
      sectionName: '2do Grado, sección: B',
      sectionImg,
      sectionStudents: [
        'Kleiber Rangel',
        'Delinyer Torres',
        'Gabriel Castillo',
        'Rihanna  Espinoza',
        'Gabriel Gil',
        'Diana Ramírez',
        'Jhoybert Ache',
        'Matías Rosales',
        'Edwin Castillo',
        'Eyan Arvelo',
        'Keinner Osta',
        'Samanta Moron',
        'Gerardo Cuenca',
        'Erick Sabala',
        'Joselin Granadillo',
        'Daniel Parra',
        'Rosibel Sierra',
        'Luis Blanco',
        'Bayolet Mendoza',
      ],
      sectionGrade: '2',
    },
    {
      sectionName: '3er Grado, sección: A',
      sectionImg,
      sectionStudents: [
        'Samira Rodríguez ',
        'Nataly Villegas',
        'Deyver  Gutierrez',
        'Jose Lucena ',
        'Stefhany España',
        'Cristopher Rengifo ',
        'Moises  Gamarra',
        'Engery Alvarado',
        'Daikeny Gerber',
        'Milkelis Manaure',
        'Karelys Mulato',
        'Adonis Giron',
        'Sophia Herrada ',
        'Andrea Pulido',
        'Leonardo Sanchez',
        'Naherobis Morillo',
        'Jonaiker Solano',
        'Genesis Osal',
        'Santiago Aliendo',
        'Diego Aliendo',
        'Miguel  Ladera',
        'Esther Mendoza ',
      ],
      sectionGrade: '3',
    },
    {
      sectionName: '3er Grado, sección: B',
      sectionImg,
      sectionStudents: [
        'Valeria García',
        'Danny  Mejia',
        'Roimer Reina',
        'Sonnary Herrera',
        'Julianysmar Carrero',
        'Jarvelys Yebsco',
        'Antonhy Damarases',
        'Suhid Cordero',
        'Darkelis Cardozo',
        'Daanubi Guerra',
        'Ashley Valentina Pacheco',
        'Nazareth Ramírez',
        'Jeiner Narvaez',
        'Dixon Ramírez',
        'Eva Colón',
        'Sebastián Bastida',
        'Danexy Izquiel',
        'Samuel Rodríguez',
        'Eskleidy Montesino',
        'Reniel Toledo',
        'Diana Pacheco',
        'Sair Cordero',
      ],
      sectionGrade: '3',
    },
    {
      sectionName: '4to Grado, sección: A',
      sectionImg,
      sectionStudents: [
        'Valeria  Abreu',
        'Cristian Acosta ',
        'Mahatma Blanco ',
        'Omar Cabeza',
        'Daylith Campos ',
        'Adrian  Castrillo',
        'Marianyely Cedeño ',
        'Cristberlin Cedeño',
        'Camila Coronado',
        'Karelis Duran',
        'Jose Flores ',
        'Dianneli Gonzalez ',
        'Estefania Gonzalez ',
        'Deivis Gutiérrez ',
        'Yoiber Mendoza ',
        'Albert Muria',
        'Dalysmel Ortiz',
        'Aaron Peralta',
        'Angel  Rivero',
        'Saviel Rodiguez',
        'Yulienny Rodríguez ',
        'Sebastian Suarez',
        'Nicol Zuñiga',
        'Yenis Vargas ',
        'Iriannys Urbina',
        'Marielis Atuñez',
        'Lucely Loaiza',
      ],
      sectionGrade: '4',
    },
    {
      sectionName: '4to Grado, sección: B',
      sectionImg,
      sectionStudents: [
        'Luciana Perry',
        'Ariannys Fumero',
        'Ariannys Guerra',
        'Jhoiner Ache',
        'Ezequiel Moncada',
        'Susej Mendez',
        'Mariangel Gómez',
        'Fernando Ramírez',
        'Jiorgelis Rodríguez',
        'Carwin Castillo',
        'Jarelys Sabala',
        'Marianny Jiménez',
        'Diliyer Flores',
        'Rachelle Hernández',
        'Aslhey Ruíz',
        'Abraham Martínez',
        'Harviet Delgado',
        'Kristian Lizarraga',
        'Sebastián Álvarez',
        'Albanis Duran',
        'Dana Ron',
        'Santiago Rosales',
        'Lucely Loviza',
        'José Gutiérrez',
        'Luciana  Perry',
        'Georgelis Avendaño',
        'Fernando Ramírez',
      ],
      sectionGrade: '4',
    },
    {
      sectionName: '5to Grado, sección: U',
      sectionImg,
      sectionStudents: [
        'Amada  Ramírez',
        'Scarlet Piñango',
        'Cristian Guaregua',
        'Luis  Astor',
        'Valeria Lombardi',
        'Moisés Soto',
        'Esael Ramos',
        'Samuel Romero',
        'Darwinson Belisario',
        'Dixon Pacheco',
        'Sebastian Navas',
        'Erick Salazar',
      ],
      sectionGrade: '5',
    },
    {
      sectionName: '6to Grado, sección: U',
      sectionImg,
      sectionStudents: [
        'Yaslevis González',
        'Willians Tribiño',
        'Stefany Hernández',
        'Isai Vega',
        'Danielys Escobar',
        'Sebastian Maldonado',
        'Pablo Osal',
        'Ronuliz Alfonso',
        'Camila Ramírez',
        'Moises Salas',
        'Eglve Jiménez',
        'Sebastián Mendoza',
        'Diego Maldonado',
        'Santiago Navas',
        'Josué Arvelo',
        'Gabriel Rivero',
        'Krismar Camejo',
        'Christian Plaza',
        'Gabriel Seducia',
        'Franyer Rondon',
        'Ángel Zambrano',
        'Julian Castillo',
        'Franyelys Castillo',
        'Denyer Aular',
        'Anailyn Duran',
        'Javier Zamora',
        'Kimberly Lizarraga',
        'Dariagnis Granado',
        'Oscar Herrera',
        'Egleanny Gutiérrez',
        'Samuel Guedez',
        'Ismel Herrera',
        'Estefany Gómez',
        'Jhosverth Maestre',
        'María Contreras',
        'Franyely Chuello',
      ],
      sectionGrade: '6',
    },
  ],
  lapses: [
    {
      lapseName: 'Primer lapso',
      diagnosticReading: {
        diagnosticText: 'Diagnóstico de lectura',
        diagnosticTable: [
          ['Grado', 'Sección', 'Resultado de lectura', 'Índice de lectura'],
          ['2do Grado', 'A', '18', '0.304'],
          ['3er Grado', 'A', '38', '0.447'],
          ['4to Grado', 'A', '43', '0.436'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText: 'Gráfico estadístico del diagnóstico de lectura',
        diagnosticGraphic: null,
      },
      diagnosticMath: {
        diagnosticText: 'Diagnóstico de multiplicación',
        diagnosticTable: [
          [
            'Grado',
            'Sección',
            'Resultado de multiplicación',
            'Índice de multiplicación',
          ],
          ['3er Grado', 'A', '13', '0.443'],
          ['4to Grado', 'A', '7', '0.233'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText:
          'Gráfico estadístico del diagnóstico de multiplicación',
        diagnosticGraphic: null,
      },
      diagnosticLogic: {
        diagnosticText: 'Diagnóstico de razonamiento lógico - matemático',
        diagnosticTable: [
          [
            'Grado',
            'Sección',
            'Resultado de lógica matemática',
            'Índice de lógica matemática',
          ],
          ['3er Grado', 'A', '1', '0.11'],
          ['4to Grado', 'A', '1', '0.111'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText:
          'Gráfico estadístico del diagnóstico de razonamiento lógico - matemático',
        diagnosticGraphic: null,
      },
      activities: [
        {
          name: 'Taller inicial',
          description: null,
          images: null,
        },
        {
          name: 'AmbLeMonedas',
          description: null,
          images: null,
        },
        {
          name: 'AmbLEncuentro',
          description:
            '      Es un Taller planificado con dinámicas innovadoras, recreativas y lúdicas para fomentar los valores de confianza, trabajo en equipo, liderazgo, comunicación y otros. Desde Fundación AmbLeMa se establecen los contenidos, las estrategias y ponentes para cada Taller. A cada coordinador se le envía un breve tutorial con los lineamientos y requerimientos necesarios para la planificación y desarrollo del taller.\n      En tal sentido, el 11 de octubre los docentes de ambos turnos se dieron cita en la institución para ser protagonistas del AmbLEncuentro 2021/2022. La jornada fue oportuna para refrescar conocimientos relacionados con las 4C (4 competencias para enfrentar los desafíos del siglo XXI) presentados meses atrás. En esta ocasión, añadimos los 7 Hábitos de la gente altamente efectiva, quedando la fórmula de la siguiente manera: 7H+4C=HQS\n      Con esa premisa se fundaron las bases para iniciar con buen pie el año escolar, haciendo énfasis en la necesidad de aplicar los diagnósticos para medir el progreso y en poner en práctica las diferentes estrategias sugeridas por AmbLeMa para alcanzar las metas propuestas. Para finalizar, los asistentes pudieron, oler, saborear y disfrutar unas deliciosas chupetas de chocolate, mientras conocían el PROAMB de este año denominado: Bosque de Chocolate.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/1/617bfdc3c69d4ab3e2824671.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/1/617bfdc3c69d4ab3e2824672.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/1/617bfdc3c69d4ab3e2824673.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/2/617c08adc69d4ab3e2824689.jpeg',
          ],
        },
        {
          name: 'Historia del cacao en Venezuela',
          description:
            '      Cada semana, el equipo creativo de Fundación AmbLeMa, prepara fascinantes historias, acompañadas de diversas estrategias que forman parte de las guías quincenales que hacemos llegar a los docentes, quienes posteriormente las incluyen en su planificación mensual.\n     De ese modo, nuestros estudiantes aprenden todo lo relacionado con la historia del cacao en Venezuela. Los personajes de Amblevilla, Mamá Pacha, AlfaBeta e Ingenio también participan para poner en marcha el Proyecto Ambiental del año escolar en curso: el Bosque de Chocolate. \n  Con este interesante material, cae por tierra el mito de que el cacao es originario de México y se invita a los estudiantes a valorar tan importante fruto. Ahora en cada escuela donde aplicamos la herramienta AmbLeMa, aprendemos que gracias a los estudios realizados por el geógrafo y botánico suizo Henri Pittier, se confirma que fue en el Arco de Maruma, estado Zulia, donde se encontraron las primeras plantas de cacao. \n      En el proceso de enseñanza además participa Cacaotín, un títere que acompaña en cada aventura. Junto a él aprendemos canciones, coreografías y cuentos divertidos relacionados con el chocolate. También conocemos los tipos de cacao y como fue la unión del cacao Criollo y el Forastero para dar origen al Trinitario. Es importante destacar, que mientras nos paseamos por la interesante historia del cacao, fomentamos el hábito de la lectura y la práctica de la matemática; así nos preparamos para un año escolar maravilloso lleno de grandes aventuras con sabor a chocolate.   ',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/3/61ae7a24e4a5597fdbe3088a.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/3/61ae7a25e4a5597fdbe3088b.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/3/61ae7a25e4a5597fdbe3088c.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/10/61b6c5a1ff5c8d90167857dc.jpeg',
          ],
        },
        {
          name: 'Características de la mazorca de cacao',
          description:
            '      Resulta curioso entrar a un aula de clases y preguntar: ¿A quién le gusta el chocolate? Todos enseguida y casi sin pensarlo, a mí... Otra pregunta: ¿A quién le gusta el olor del chocolate? El resultado es el mismo, a todos... Una última pregunta: ¿De qué fruto viene el chocolate? Casi nadie acertó.\n      Partiendo de esas tres preguntas, la coordinadora abre un interesante debate sobre el cacao, su historia y su singular apariencia. Les explicamos que el chocolate se realiza con las semillas de cacao y estas vienen dentro de una mazorca. \n      Para hablar sobre la mazorca y sus partes invitamos a Cacaotín. Junto a él pudimos interactuar y compartir los conocimientos previos de los niños, así como algunas curiosidades  sobre el chocolate. \n      La actividad permitió tener experiencias maravillosas con los estudiantes, ya que algunos pudieron ver como se abre la mazorca, se enteraron qué ellas crecen pegadas al tronco, vieron como son las semillas, e incluso, un grupo pudo oler y hasta probar el fruto. \n      Dicha jornada nos llevó a una conclusión: aunque a todos nos gusta el chocolate, muy pocos conocíamos sobre el fruto, de allí la importancia de ser curiosos y preguntarnos de dónde viene todo lo que consumimos. \nSin duda los estudiantes disfrutaron una experiencia agradable y enriquecedora gracias al PROAMB.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/4/61ae7d9ce4a5597fdbe3088f.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/4/61ae7d9ce4a5597fdbe30890.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/4/61ae7d9ce4a5597fdbe30891.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/4/61ae7d9ce4a5597fdbe30892.jpeg',
          ],
        },
        {
          name: 'Siembra de cacao',
          description: null,
          images: null,
        },
        {
          name: 'JUMP Math',
          description: null,
          images: null,
        },
        {
          name: 'PROAMB... Una experiencia con sabor a chocolate',
          description:
            '      Este año, la propuesta ambiental lleva por nombre "Bosque de Chocolate" con cada guía semanal queremos fomentar entre los docentes y estudiantes de la escuela un mayor conocimiento de algo tan propio y originario de nuestro país: el Cacao. A través de 10 Ecotemas, distribuidos en los tres lapsos del año escolar, estamos recorriendo toda la información necesaria para conocer desde la historia del cacao, sus características, su cultivo y procesamiento; hasta llegar a las fases para la elaboración del chocolate. Incluyendo temas relacionados con las aves cacaoteras y las tradiciones culturales que hacen referencia al cacao o al chocolate.\n      El objetivo es que con los conocimientos que adquieran en la escuela los niños puedan, en la actividad final del año escolar, con el apoyo de sus docentes organizar lo que llamamos el Bosque de Chocolate de la escuela; donde expongan, de modo creativo, en un circuito de diversas estaciones con los temas que hacen referencia al cacao y el chocolate. Cada Ecotema que proponemos desde AmbLeMa incluye una actividad teórica y una dinámica divertida para que, de modo ameno, puedan conocer algo tan nuestro y lo que sepan enseñar a otros. Desde el origen del cacao hasta la elaboración de ricas barras de chocolate en la escuela. Desde AmbLeMa brindamos experiencias enriquecedoras que garantizan un año lleno de dulces aventuras con sabor a chocolate.\n',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/5/61ae7e92e4a5597fdbe30893.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/5/61ae7e92e4a5597fdbe30894.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/5/61ae7e92e4a5597fdbe30895.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/5/61ae7e93e4a5597fdbe30896.jpeg',
          ],
        },
        {
          name: 'Plan Lector... Todos A Leer',
          description:
            '      Como ya es sabido por todos, uno de los pilares de AmbLeMa es la lectura, así que, constantemente nos dedicamos a resaltar la importancia de leer con fluidez y entender lo que leemos. En este sentido, cada propuesta emanada desde el equipo creativo, invita a alimentar el amor por la lectura. La idea es que ya sea en casa o en la escuela, cada estudiante dedique 9 minutos ½ diarios para leer. \n      A esa actividad en AmbLeMa se le conoce como la Hora TAL (Todos A Leer), lo que buscamos con dicha estrategia es que grandes y chicos tengan el maravilloso hábito de la lectura. Además de esa estrategia, preparamos otras actividades de comprensión lectora y brindamos orientación tanto a docentes como a representantes para que apoyen a sus estudiantes según el nivel en el que se encuentre.\n      ¿Cómo sabemos cuánto lee cada estudiante?, ¿De qué manera sabemos si realmente el estudiante está progresando? Con el lectómetro, una herramienta de medición que nos permite cuantificar cuántas palabras por minuto logra leer cada niño. El lectómetro es un cuadro donde se refleja la cantidad de palabras por minuto leída con su fecha. Cada docente indica al representante y a los alumnos la meta de lectura que corresponde a su grado.\n      En nuestra escuela los docentes recomiendan que se haga uso del lectómetro al menos una vez por semana para comprobar los avances individuales. ',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/9/61b2c6ac4b97c4d4a22961aa.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/9/61b2c6ac4b97c4d4a22961ab.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/9/61b2c6ac4b97c4d4a22961ac.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/9/61b2c6ac4b97c4d4a22961ad.jpeg',
          ],
        },
        {
          name: 'Plan Matemática... Calcula, piensa y juega',
          description:
            '      ¿Quién dijo que las matemáticas daban miedo o que eran algo aburrido? En AmbLeMa tenemos claro que las matemáticas nos acompañan constantemente aunque no lo notemos. Mira a tu alrededor y descubre que hay figuras geométricas y números por doquier.\n      Aunque nos parezca mentira, no podemos escapar de las matemáticas, ellas están presente a lo largo de toda nuestra vida, así que no hay razones para hacerlo cada vez más complicado. En AmbLeMa descubrimos esa gran verdad, por eso estamos interesados en desarrollar el pensamiento lógico matemático en cada estudiante. Lo logramos invitando a los docentes a incluir dentro de su planificación ejercicios que van de lo sencillo a lo más complejo. \n      Además, queremos lograr que haya mayor dominio de las operaciones básicas como suma, resta y multiplicación. Por esa razón, en cada guía plasmamos ejercicios con los cuales los estudiantes puedan aprender las matemáticas y divertirse durante dicho proceso. Por otro lado, al adquirir conocimientos matemáticos, nos vamos entrenando para participar en las Olimpiadas Recreativas de Matemáticas que se realiza todos los años en Venezuela. \n      Éste año, la meta es logra varias medallas en dicho evento. Pudiera sonar difícil, pero es nuestra meta y estamos seguros que juntos podemos lograrlo.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/8/61b2c3704b97c4d4a22961a6.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/8/61b2c3704b97c4d4a22961a7.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/8/61b2c3704b97c4d4a22961a8.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/11/61b6c5d9ff5c8d90167857dd.jpeg',
          ],
        },
        {
          name: 'Diagnósticos... En AmbLeMa todo se mide',
          description:
            '      Cuando queremos saber cómo vamos en relación a las metas, es necesario MEDIR. Esa es la razón de ser de los diagnósticos que hacemos en cada una de las escuelas como parte importante de la aplicación de AmbLeMa. Los diagnósticos son realizados a los estudiantes en tres áreas esenciales: lectura fluida, dominio de las multiplicaciones y razonamiento lógico-matemático. \n      La estrategia la llevamos a cabo en tres momentos del año: el diagnóstico inicial ( durante el mes de octubre), su objetivo es conocer cómo están los niños al comenzar el año escolar. Posteriormente, aplicamos el test de revisión, a la mitad del año escolar (en el mes de marzo) con el fin de evaluar los avances y por último,  el test final para ver como están con las metas propuestas.\n      Si, unas metas en cada área. Para cada grado proponemos a los docentes unas metas, en las áreas de lectura y matemáticas, que esperamos se alcancen para el final del año; como consecuencia de la aplicación de las estrategias propias de AmbLeMa. En éste sentido, para realizar los diagnósticos contamos con un material previamente revisado y cada coordinador AmbLeMa, con el apoyo de algunos docentes, se lo aplica a los estudiantes. \n      Posteriormente, los resultados del diagnóstico, por cada grado, son tabulados, graficados y compartidos para que los docentes sepan por donde van y cuánto falta para llegar a las metas. Al aplicar cada  diagnóstico en nuestra escuela, sabemos en qué área de aprendizaje se encuentra el estudiante, así  y podemos plantear estrategias para llegar la meta o mantenerse en ella. ',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/6/61aec852e4a5597fdbe3091f.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/6/61aec852e4a5597fdbe30920.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/6/61aec852e4a5597fdbe30921.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/7/61b2aeea4b97c4d4a229619f.jpeg',
          ],
        },
      ],
    },
    {
      lapseName: 'Segundo lapso',
      diagnosticReading: {
        diagnosticText: 'Diagnóstico de lectura',
        diagnosticTable: [
          ['Grado', 'Sección', 'Resultado de lectura', 'Índice de lectura'],
          ['2do Grado', 'A', '30', '0.507'],
          ['2do Grado', 'B', '25', '0.427'],
          ['3er Grado', 'A', '39', '0.458'],
          ['3er Grado', 'B', '42', '0.495'],
          ['4to Grado', 'A', '52', '0.521'],
          ['5to Grado', 'U', '63', '0.557'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText: 'Gráfico estadístico del diagnóstico de lectura',
        diagnosticGraphic: null,
      },
      diagnosticMath: {
        diagnosticText: 'Diagnóstico de multiplicación',
        diagnosticTable: [
          [
            'Grado',
            'Sección',
            'Resultado de multiplicación',
            'Índice de multiplicación',
          ],
          ['3er Grado', 'A', '10', '0.343'],
          ['3er Grado', 'B', '8', '0.277'],
          ['4to Grado', 'A', '13', '0.444'],
          ['4to Grado', 'B', '5', '0.189'],
          ['5to Grado', 'U', '14', '0.481'],
          ['6to Grado', 'U', '11', '0.389'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText:
          'Gráfico estadístico del diagnóstico de multiplicación',
        diagnosticGraphic: null,
      },
      diagnosticLogic: {
        diagnosticText: 'Diagnóstico de razonamiento lógico - matemático',
        diagnosticTable: [
          [
            'Grado',
            'Sección',
            'Resultado de lógica matemática',
            'Índice de lógica matemática',
          ],
          ['3er Grado', 'A', '1', '0.096'],
          ['3er Grado', 'B', '1', '0.11'],
          ['4to Grado', 'A', '2', '0.144'],
          ['4to Grado', 'B', '2', '0.134'],
          ['5to Grado', 'U', '2', '0.185'],
          ['6to Grado', 'U', '1', '0.127'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText:
          'Gráfico estadístico del diagnóstico de razonamiento lógico - matemático',
        diagnosticGraphic: null,
      },
      activities: [
        {
          name: 'Olimpíadas matemáticas',
          description:
            'El mes de marzo llegó cargado de muchas actividades, en esta ocasión hablamos de las Olimpiadas Recreativas de Matemáticas (ORM), allí un grupo de estudiantes logró participar en la jornada que reúne niños y niñas de distintas instituciones de todo el territorio nacional, cabe destacar que están incluidas escuelas públicas y privadas.\nPara la U.E.E. Santa Inés, este es el tercer año participando en dicho evento, en el que se pone a prueba las habilidades y destrezas de los estudiantes en cuanto a las matemáticas se refiere.\nHay que destacar que, en las dos ediciones anteriores, por motivo de la pandemia, la mayoría de las pruebas fueron en modalidad virtual, lo que impidió la participación masiva de alumnos, sin embargo, este año fue posible aplicar un mayor número de pruebas.\nLa jornada fue posible gracias al trabajo en equipo y el compromiso tanto de docentes, directivo y representantes. Aplaudimos el esfuerzo de los estudiantes Camila Coronado y Lucely Loaiza, ambas de 4to grado, quienes lograron clasificar a la fase regional de las Olimpiadas, dejando en alto el nombre de la U.E.E. Santa Inés. \nDesde AmbLeMa, seguimos enfocados en una educación de calidad, por lo que quincenalmente enviamos guías de actividades que van ampliando los conocimientos matemáticos y despertando la curiosidad, de tal modo que cada vez puedan tener un mejor desempeño en las ORM.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/17/625837d27248374344cd947c.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/17/625837d27248374344cd947d.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/17/625837d27248374344cd947e.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/17/625837d27248374344cd947f.jpeg',
          ],
        },
        {
          name: 'Los maestros, protagonistas de nuestra historia...',
          description:
            'Cada 15 de enero, en Venezuela se celebra el Día del Maestro, en este sentido, desde Fundación AmbLeMa tenemos por costumbre brindar un merecido homenaje a los docentes, esos hombres y mujeres que se levantan cada mañana con un objetivo en mente: educar.\nEsos que, apegados a su vocación suman voluntades a favor de los más pequeños, que pese a las adversidades siguen en pie, abrazados a una esperanza: lograr que haya una educación de calidad en Venezuela, esos que dicen a voz en cuello cada vez que hay un nuevo desafío: "Hagamos Que Suceda"\nCon motivo de celebrar ese día especial, los docentes de la U.E.E. Santa Inés se dieron cita en las instalaciones del plantel para compartir juntos, entre otras cosas, un delicioso sancocho a leña. La ocasión también se prestó para conversar sobre las propuestas de AmbLeMa para los próximos meses.\nFinalmente, cada maestro pudo degustar un delicioso chocolate, a propósito de recordar el proyecto ambiental de este año (Bosque de Chocolate). Además, cada uno de los presentes recibió hermosos presentes que le serán de gran utilidad para el desarrollo de las próximas actividades educativas.\nUna vez más, desde Fundación AmbLeMa diseñamos una manera agradable de comenzar el nuevo año.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/12/61f8997df259f1b6b1aa4585.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/13/61f899e3f259f1b6b1aa4586.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/14/61f89ac3f259f1b6b1aa4587.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/15/61f89c0df259f1b6b1aa4588.jpeg',
          ],
        },
        {
          name: '¿Cosechamos juntos?',
          description:
            'La siembra es uno de los procesos de aprendizaje que nos enseñan a valorar la vida, cuando siembras una planta te interesas por cuidarla, atender a sus necesidades y ser parte del desarrollo. Pero la mayor de las dichas surge cuando llega cuando vemos sus primeras flores, todo indica que pronto vendrá el fruto. \nEsto es lo que ocurre en nuestra escuela, sembramos la planta de cacao y aunque falta mucho camino por recorrer, en AmbLeMa les mostramos mediante las guías, lo que va a pasar cuando aparezcan las primeras flores, cuanto tiempo pasará para que llegue el fruto a su madurez y cuando estará listo para ser cosechado. \n¿De qué manera lo hicimos? con la creación del ”cosechometro”, instrumento que sirve para reconocer mediante una escala de colores, cual es el momento ideal de la mazorca de cacao para ser desprendida del tronco. \nAdemás, aprendimos cual es la técnica para bajar la mazorca sin dañar la corteza. La experiencia nos ayudó a sumergirnos en el maravilloso mundo del cultivo de cacao. Durante las actividades, los niños pudieron conocer las partes de la mazorca, oler el fruto y un grupo llegó a probarlo.  De este modo nos vamos preparando para el Bosque de Chocolate. ',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/21/62ab0594d6667ab81653af5c.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/21/62ab0594d6667ab81653af5d.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/21/62ab0594d6667ab81653af5e.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/21/62ab0594d6667ab81653af5f.jpeg',
          ],
        },
        {
          name: 'Paso a paso vamos avanzando',
          description:
            'Postcosecha, un término que quizá para muchos suene algo complejo, pero en AmbLeMa lo explicamos de un modo sencillo: las acciones que se realizan luego de haber cosechado las mazorcas de cacao. \nEn esta etapa, los niños conocen el procesamiento y preparación del cacao para obtener un chocolate de excelente calidad. Proveemos a los docentes de una guía completa, que detalla la importancia de la fermentación. \nEn este tramo del camino, también aprendemos un paso crucial en el sabor del chocolate, se trata del secado, para explicarlo quien mejor que Cacaotín, la mascota oficial del Bosque de Chocolate, él mediante un fascinante video, nos indica todo el proceso: selección de mazorcas, fermentación, secado y añejamiento.  \nCabe destacar, que como complemento de la actividad, los estudiantes hicieron hermosos y originales móviles con material de provecho, estos, debían estar relacionados con los pasos de la postcosecha.  \nAhora, tanto estudiantes como docentes, saben por qué tenemos el mejor chocolate del mundo: sencillo, porque nuestros productores cuidan cada detalle. \nAsí es como avanzamos paso a paso para lograr que nuestros estudiantes puedan dominar el tema y se preparen para exponer dichos conocimientos al final del año escolar en nuestro Bosque de Chocolate. ',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/22/62ab062dd6667ab81653af60.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/22/62ab062dd6667ab81653af61.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/22/62ab062dd6667ab81653af62.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/22/62ab062dd6667ab81653af63.jpeg',
          ],
        },
        {
          name: 'Juntos en un solo lugar...',
          description:
            'Mamá Pacha nos acompaña a conocer un tema super interesante: ecosistema y cacao. Junto ella nuestros estudiantes descubren que hay una gran diversidad de insectos, aves, reptiles y plantas que forman parte del cultivo de cacao.\nAl llegar a este punto, hablamos de los ecosistemas naturales y la interacción de las especies que viven juntas en el Bosque de Chocolate. También nos adentramos en el maravilloso mundo de las curiosidades animales. Descubriendo así, que insectos como la mosquita, las abejas, las mariposas y arañas, están allí por algo, y cada quien tienen una misión.\nJuntos, maestros y niños, también aprenden que hay plantas de flores exóticas como el famoso Bastón de Faraón, que están muy relacionadas con el cacao y que hay árboles que crean las condiciones ideales para un buen cultivo. \nLuego de conocer la fauna y flora que compone el ecosistema natural del cacao, los estudiantes fueron desafiados mediante lo que conocemos en AmbLeMa como una Eco-Tarea, para que realizaran en casa, con la ayuda de sus representes, el dibujo de un animal imaginario.\nPara dicha actividad, podían mezclar tres animales que ellos consideraran que podían vivir en la plantación de cacao y mencionar tres características de dicho animal. El derroche de creatividad no se hizo esperar. ',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/20/62aa978bd6667ab81653af3b.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/20/62aa978bd6667ab81653af3c.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/20/62aa978bd6667ab81653af3d.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/20/62aa978cd6667ab81653af3e.jpeg',
          ],
        },
        {
          name: 'Prueba ORM',
          description: null,
          images: null,
        },
        {
          name: 'Concurso Papagayo',
          description: null,
          images: null,
        },
        {
          name: 'Reto AmbLeMa',
          description:
            'El mes de marzo nos sorprendió gratamente, pues luego de tan larga espera debido a la pandemia, llegó el gran día, finalmente los niños fueron protagonistas del gran Reto AmbLeMa 2022. Una dicha ver nuestra escuela llena de niños después de tanto tiempo. \nAfortunadamente, la institución cuenta con un gran terreno que permitió desarrollar las actividades en cada estación, siendo cuidadosos con el cumplimiento de las normas de bioseguridad. \nLas risas, gritos y algarabía nuevamente se hicieron sentir en cada espacio, una maravilla… Así comenzó la aventura, un recorrido por siete estaciones que nos recordaban lo que hacemos en AmbLeMa cada año escolar: Bosque de Chocolate, Venezuela Megadiversa y Feria Científica. \nAdemás, en otro espacio, nuestros chicos debían realizar una carrera de sacos para luego responder preguntas de lógica matemática. Jugaron a las Charadas en la Zona TAL (Todos A Leer) y por si fuera poco hicieron fascinantes figuras en una estación denominada el Laboratorio de Matemagia.\nDespués de tanta emoción, poco a poco fueron llegando a uno de los lugares más esperados, a la puerta de la bodega, para así, canjear sus AmbleMonedas acumuladas desde el inicio del año escolar y adquirir ricas golosinas. Cada quien compró en la bodega según la cantidad de monedas que se ganó con tanto esfuerzo, de este modo reforzamos uno de nuestros principios: En AmbLeMa, no se regala, se gana…',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/18/62aa95eed6667ab81653af33.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/18/62aa95efd6667ab81653af34.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/18/62aa95efd6667ab81653af35.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/18/62aa95efd6667ab81653af36.jpeg',
          ],
        },
        {
          name: 'Medir para comparar...',
          description:
            'Fundación AmbLeMa aplica tres diagnósticos durante el año escolar para evaluar la efectividad de la herramienta, en este lapso corresponde el diagnóstico de revisión. El objetivo es comparar el alcance de la aplicación de la herramienta en los niños. Para ello, aplicamos los diagnósticos de la misma manera que lo hicimos en el primer lapso. Obtenido los resultados procedemos a compararlos con el diagnóstico inicial.\n En tal sentido, observamos que en esta oportunidad en el diagnóstico de lectura participó el 29 % de la matrícula, 2 % menos que en el anterior. Los rangos de índices promedios oscilan entre 0.43 y 0.56, a diferencia del primer lapso que oscilaban entre 0.3 y 0.45\nCon relación al diagnóstico de multiplicación, participó un 23 % de la matrícula, 23 % menos que el primer lapso. Los índices promedios oscilan entre 0.19 y 0.48, a diferencia del primer lapso que oscilaban entre 0.23 y 0.44, se evidencia progreso en algunos grados y en otros retrocesos.\n Por otra parte, la participación en el diagnóstico de lógica fue también del 23 %.  Los índices promedios oscilan entre 0.1 y 0.18, a diferencia del primer lapso que se ubicaban en 0.11. Hasta la fecha, aún los alumnos no alcanzas las metas establecidas, requiriéndose una mayor constancia en la aplicación de las estrategias sugeridas por AmbLeMa.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/25/62d32cdf7786bc408f4cddec.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/25/62d32cdf7786bc408f4cdded.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/25/62d32cdf7786bc408f4cddee.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/25/62d32cdf7786bc408f4cddef.jpeg',
          ],
        },
        {
          name: 'Olimpiada Recreativa de Lenguaje',
          description:
            'Desde el 29 al 31 de marzo de 2022 nuestra escuela se llenó de emoción durante la primera edición de las Olimpiadas Recreativas de Lenguaje. El evento no les tomó por sorpresa, ya que, desde que AmbLeMa llegó a la escuela, los estudiantes practican la Hora TAL (Todos A Leer), así que, están acostumbramos a realizar diariamente un tiempo de lectura, que incluye actividades de comprensión lectora, puntuación y redacción, entre otros. \nCabe destacar que, la evaluación preliminar se realizó de manera presencial, en la institución, allí logramos la dicha de que cuatro de nuestros estudiantes clasificaron a la fase regional pautada para el 24 de mayo 2022. \nLos estudiantes clasificados a la fase regional de las ORL fueron: José Lucena (3ro A), Camila Coronado (4to A), Moisés Soto (5to U) y Franyer Rondón (6to U)\nLo que se vivió en las Olimpiadas Recreativas de Lenguaje fue una expresión de múltiples saberes… Un acontecimiento sin precedentes, donde además de ponerse a prueba nociones de lenguaje y literatura, hubo que vencer otro tipo de obstáculos a nivel tecnológico y de conectividad, ya que esta segunda fase fue de manera virtual. \nPodemos decir que, la experiencia dejó como resultado una mayor cantidad de docentes y niños motivados a seguir avanzando en los objetivos propuestos desde Fundación AmbLeMa, para lograr tener mayor cantidad de estudiantes clasificados en las próximas competencias.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/19/62aa96afd6667ab81653af37.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/19/62aa96b0d6667ab81653af38.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/19/62aa96b0d6667ab81653af39.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/19/62aa96b0d6667ab81653af3a.jpeg',
          ],
        },
      ],
    },
    {
      lapseName: 'Tercer lapso',
      diagnosticReading: {
        diagnosticText: 'Diagnóstico de lectura',
        diagnosticTable: [
          ['Grado', 'Sección', 'Resultado de lectura', 'Índice de lectura'],
          ['2do Grado', 'A', '42', '0.706'],
          ['2do Grado', 'B', '27', '0.465'],
          ['3er Grado', 'A', '65', '0.772'],
          ['3er Grado', 'B', '77', '0.908'],
          ['4to Grado', 'A', '85', '0.854'],
          ['4to Grado', 'B', '72', '0.729'],
          ['5to Grado', 'U', '76', '0.665'],
          ['6to Grado', 'U', '95', '0.762'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText: 'Gráfico estadístico del diagnóstico de lectura',
        diagnosticGraphic: null,
      },
      diagnosticMath: {
        diagnosticText: 'Diagnóstico de multiplicación',
        diagnosticTable: [
          [
            'Grado',
            'Sección',
            'Resultado de multiplicación',
            'Índice de multiplicación',
          ],
          ['3er Grado', 'A', '14', '0.47'],
          ['3er Grado', 'B', '12', '0.421'],
          ['4to Grado', 'A', '20', '0.683'],
          ['4to Grado', 'B', '18', '0.614'],
          ['5to Grado', 'U', '15', '0.525'],
          ['6to Grado', 'U', '21', '0.702'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText:
          'Gráfico estadístico del diagnóstico de multiplicación',
        diagnosticGraphic: null,
      },
      diagnosticLogic: {
        diagnosticText: 'Diagnóstico de razonamiento lógico - matemático',
        diagnosticTable: [
          [
            'Grado',
            'Sección',
            'Resultado de lógica matemática',
            'Índice de lógica matemática',
          ],
          ['3er Grado', 'A', '3', '0.211'],
          ['3er Grado', 'B', '2', '0.167'],
          ['4to Grado', 'A', '3', '0.239'],
          ['4to Grado', 'B', '2', '0.188'],
          ['5to Grado', 'U', '3', '0.23'],
          ['6to Grado', 'U', '4', '0.27'],
        ],
        diagnosticAnalysis: null,
        diagnosticGraphicText:
          'Gráfico estadístico del diagnóstico de razonamiento lógico - matemático',
        diagnosticGraphic: null,
      },
      activities: [
        {
          name: '¿Cómo se transforma el cacao en chocolate?',
          description:
            'Fundación AmbLeMa, como parte del proyecto ambiental de este año escolar “Bosque de Chocolate”, propuso para el tercer momento dar a conocer el proceso por el cual debe pasar el cacao para convertirse en chocolate. Parte de las actividades fue discutir sobre todo lo que se puede lograr con la pasta de cacao: batidos, helados, galletas, tortas, postres varios, chocolate en barra y bombones, entre otros. \nCabe destacar, que, mediante las guías, invitamos a los estudiantes a crear recetarios de chocolate y como era de esperarse, la creatividad se desbordó. Sin duda, fue un momento agradable, donde surgieron las más extrañas y deliciosas recetas a base de chocolate. Se hizo énfasis en que la Choco-Fabrica del Bosque de Chocolate, sería el lugar ideal para exponer las mejores recetas de cada salón. \nLuego de varias actividades, pasamos de la teoría a la práctica, así que, invitamos a Zurin Fernández, en directivo de Chamos FVAC, quien, junto a una distribuidora de chocolate cercano a la institución, organizaron una maravillosa jornada que incluyó: juegos, cantos y bailes. Los estudiantes, desde ese momento, se convirtieron en unos expertos chocolateros tras aprender a preparar deliciosas trufas a base de cacao.\nEn el evento, participaron los 5 estudiantes con mayor índice de lectura por cada sección. Sin lugar a dudas, la experiencia fue genial, pues cada quien preparó su propia trufa y se deleitó con el rico sabor del chocolate.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/24/62d1899b281b3475e326656d.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/24/62d1899b281b3475e326656e.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/24/62d1899b281b3475e326656f.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/24/62d1899b281b3475e3266570.jpeg',
          ],
        },
        {
          name: 'Beneficios del Chocolate para la Salud',
          description:
            'Un tema de gran importancia que quisimos destacar desde Fundación AmbLeMa este año, es el aporte que el cacao ofrece para nuestra salud y belleza. Luego de conocer detenidamente todo el proceso de siembra, cosecha y postcosecha, llegó el momento de dejar claro, que el cacao, es más que un dulce sabor para deleitar el paladar, pues constituye una fuente de grandes nutrientes que se traducen en salud y bienestar corporal. \nCreemos que al conocer las bondades del fruto, grandes y chicos podrán valorarlo cada vez más, siendo conscientes de la importancia que el mismo tiene para la economía y productividad de nuestro país. En este sentido, los estudiantes realizaron exposiciones, debates y creativos afiches. Asimismo, se invitó a los alumnos a preparar algunas choco recetas que ayudan a mejorar aspectos de la salud y la belleza corporal. \nEs importante destacar, que entre las creaciones hubo cremas corporales, manteca de cacao, baño de crema para cabellos resecos, mascarillas, jabón de chocolate, soluciones para talones y codos resecos, bebidas energéticas, te de cacao, etc. Hablar del cacao y sus bondades, sirvió como antesala para todo lo que habrá en la Botica (farmacia del pueblo) y el Choco-Spa del Bosque de Chocolate, con el cual se despedirá el año escolar 2021-2022',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/27/62d330e37786bc408f4cddf6.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/27/62d330e37786bc408f4cddf7.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/27/62d330e37786bc408f4cddf8.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/27/62d330e37786bc408f4cddf9.jpeg',
          ],
        },
        {
          name: 'Análisis de Resultados',
          description:
            'Luego de ver y comparar los tres diagnósticos realizados en nuestra institución a lo largo del año escolar 2021-2022, podemos observar que hubo un avance en la lectura, ya que el índice promedio inicial de la escuela fue de 0.39 y el final de 0.73, lo cual representa un 34 % de progreso.\nEn relación con los resultados obtenidos en el diagnóstico de matemáticas, tenemos que, en la multiplicación, el índice promedio inicial de la escuela fue de 0.33 y al final del año un 0.56, reflejando un avance de 23 %. En este sentido, nuestra meta es lograr que el índice promedio de la escuela llegue a 1, lo que significa que todos los alumnos dominen operaciones básicas de multiplicación.\nOtro de los aspectos a evaluar en AmbLeMa es el desarrollo del pensamiento lógico matemático, en este sentido, tenemos que, el índice promedio inicial de la escuela pasó de 0.11 a 0.21, es decir, un 10 % de progreso. Los resultados demuestran que los estudiantes requieren de un mayor esfuerzo para alcanzar las metas relacionadas con la resolución de problemas de lógica. \nEs importante tomar en cuenta, que, aunque la mayoría de los alumnos no logró alcanzar las metas establecidas de acuerdo a cada grado, para nosotros, no deja de representar un logro, tomando en cuenta, que los estudiantes retornaron a las aulas ha mediado del año en curso, luego de dos años de clases a distancia debido a la pandemia, lo que sin lugar a dudas influyó considerablemente en el rendimiento académico de los mismos.  \n',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/26/62d32d3b7786bc408f4cddf1.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/26/62d32d467786bc408f4cddf2.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/26/62d32d467786bc408f4cddf3.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/26/62d32d477786bc408f4cddf4.jpeg',
          ],
        },
        {
          name: 'Feria AmbLeMa "Bosque de Chocolate"',
          description:
            'El 6 de julio, nuestra escuela se convirtió en lugar un mágico lleno de color y sabor a cacao, una maravillosa experiencia que en AmbLeMa se le conoce como Bosque de Chocolate. \nDesde tempranas horas de la mañana las calles del sector estaban llenas de personas con plantas, adornos, flores, disfraces, afiches, entre otros. Todo parecía indicar que algo estaba a punto de suceder. Cuando el reloj marcó las 9:30 de la mañana se dio inicio a la fiesta más dulce de nuestra historia. \nDicha aventura comenzó con un recorrido por diversas estaciones. Primero pasamos por el Museo del Cacao, allí los chicos de preescolar lucían hermosos atuendos representando a nuestros aborígenes, además una galería de arte y estatuas vivientes. Al salir de allí, pasamos al vivero del cacao, en ese espacio se explicó todo lo relacionado con el proceso de siembra. Posteriormente, se visitó la hacienda, donde se puso de manifiesto todo el proceso de cosecha y postcosecha. \nSeguidamente, nos dirigimos a la Choco Fabrica, donde un grupo de chicos representaba a los trabajadores explicó todo el proceso por el cual pasa la semilla de cacao para llegar a convertirse en chocolate. Luego, un grupo de mini chef, compartió choco recetas e invitó a los presentes a degustar del producto final. Para culminar, llegamos a la Botica y el Choco-Spa, lugar donde se podía aprender todo sobre las bondades del cacao para la salud. \nLas actividades culturales, previstas en la plaza del cacao, se vieron interrumpidas por una fuerte lluvia, pero se retomaron cuando la misma cesó. Posteriormente, pudimos a hacer la Bodega AmbLeMa y hacer la entrega de reconocimientos a los docentes destacados durante el año escolar.',
          images: [
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/23/62d0f207281b3475e326654a.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/23/62d0f207281b3475e326654b.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/23/62d0f207281b3475e326654c.jpeg',
            'https://amblema.org/resources/images/school_years/614dab341e22a46d8605b6da/pecas/614db5e61e22a46d8605b739/yearbook/23/62d0f207281b3475e326654d.jpeg',
          ],
        },
      ],
    },
  ],
  breakForLapses: true,
}
