export const mockSchoolSections = [
  {
    sectionName: 'Preescolar, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Jhanier Antonio Blanco',
      'Jhaider Andrés Blanco',
      'Neiver Cabeza',
      'Kerstin Flores',
      'Josué Gamarra',
      'Mathias García',
      'Sara Mendoza',
      'Samira Machado',
      'Gabriela  Molina',
      'Ronald Rodríguez',
      'Marielvis Vegas',
      'Mariangely Betancourt',
      'Nicolee Castillo',
      'Jeandri Guerra',
      'Aarón Granadillo',
      'Ronald  Quintero',
      'Gianna Salcedo',
      'Jeremy Suárez',
      'Enyelber Castillo',
      'Mateo Chacón',
    ],
    sectionGrade: '0',
  },
  {
    sectionName: 'Preescolar, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Leysmar Paredes',
      'Xavier Marcano',
      'Gabriel Martínez',
      'Ezequiel Bohada',
      'Miguel  Rivas',
      'Ricardo Morillo',
      'Aurora Cobi',
      'Jeremías Moncada',
      'Luis  Fajardo',
      'Shaelot Benítez',
      'Enyerbet  Castillo',
      'Katniss Hernández',
      'Carolay Rodríguez',
      'Sophia Hinagas',
      'Manuel Peña',
      'Dereth Rodríguez',
      'Fabián Villamizar',
      'Marlon Mejías',
      'Santiago Márquez',
      'Jeremías Nieves',
      'Valery López',
    ],
    sectionGrade: '0',
  },
  {
    sectionName: '1er Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Jadriel Arcila',
      'Lesbia Camacho',
      'Ashley Flores',
      'Isabella Gallardo',
      'Kevin  Guevara ',
      'Sarah Pérez ',
      'Andrew Pérez ',
      'Luciannys Reina ',
      'Sanny Romero',
      'Mathias Garcias',
      'Samira Mendoza ',
      'Sara Mendoza',
      'Mauricio  Ribero ',
      'Ronald Rodríguez ',
      'Marielvys  Vegas',
      'Jhaider Blanco ',
      'Jhanier Blanco ',
      'Neiver  Cabeza',
      'Kerstin Flores',
      'Dereth Rodríguez ',
    ],
    sectionGrade: '1',
  },
  {
    sectionName: '1er Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Manuel Piña',
      'Ronald Quintero',
      'Gianna  Salcedo',
      'Neives Ceballos',
      'Lucia Narváez',
      'Nahomiz Olivero',
      'Fabian Campo Verde',
      'Hyller Guerra',
      'Jhosep León',
      'Rosmely Ramírez',
      'Jefferson Rojas',
      'Angel Muria',
      'Miller Aular',
      'Franchezca Flores',
      'Aranza Cordero',
      'Ciro Jaramillo',
      'Valentina Bastida',
      'Enyelber Castillo',
      'Jeandri Guerra',
    ],
    sectionGrade: '1',
  },
  {
    sectionName: '2do Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Jose Olivares',
      'Anyelit Roa',
      'Jessimar Mata',
      'Maholis Quintero',
      'Pilar Cabeza',
      'Jeliagnis Valderrama',
      'Alejandro Tovar',
      'Ivanna Prin',
      'Isaac Navarro',
      'Hendrix Bravo',
      'Isaac Almeida',
      'Antony Bastidas ',
      'Ariannilis Gonzalez',
      'Santiago Guiliarte',
      'Sleykysmar Ramírez ',
      'Betzabeth Jiménez ',
      'Jheicob Cohen',
      'Miguel Martínez ',
      'Liliana Mejías ',
      'Angelit Roa',
      'Arlegnis Valderrama',
      'Allen Velázquez ',
      'Giulianna Andrade',
      'Diego Torres',
      'Alan  Correa',
      'Gabriel  Castillo',
      'María  Suárez',
    ],
    sectionGrade: '2',
  },
  {
    sectionName: '2do Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Kleiber Rangel',
      'Delinyer Torres',
      'Gabriel Castillo',
      'Rihanna  Espinoza',
      'Gabriel Gil',
      'Diana Ramírez',
      'Jhoybert Ache',
      'Matías Rosales',
      'Edwin Castillo',
      'Eyan Arvelo',
      'Keinner Osta',
      'Samanta Moron',
      'Gerardo Cuenca',
      'Erick Sabala',
      'Joselin Granadillo',
      'Daniel Parra',
      'Rosibel Sierra',
      'Luis Blanco',
      'Bayolet Mendoza',
    ],
    sectionGrade: '2',
  },
  {
    sectionName: '3er Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Samira Rodríguez ',
      'Nataly Villegas',
      'Deyver  Gutierrez',
      'Jose Lucena ',
      'Stefhany España',
      'Cristopher Rengifo ',
      'Moises  Gamarra',
      'Engery Alvarado',
      'Daikeny Gerber',
      'Milkelis Manaure',
      'Karelys Mulato',
      'Adonis Giron',
      'Sophia Herrada ',
      'Andrea Pulido',
      'Leonardo Sanchez',
      'Naherobis Morillo',
      'Jonaiker Solano',
      'Genesis Osal',
      'Santiago Aliendo',
      'Diego Aliendo',
      'Miguel  Ladera',
      'Esther Mendoza ',
    ],
    sectionGrade: '3',
  },
  {
    sectionName: '3er Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Valeria García',
      'Danny  Mejia',
      'Roimer Reina',
      'Sonnary Herrera',
      'Julianysmar Carrero',
      'Jarvelys Yebsco',
      'Antonhy Damarases',
      'Suhid Cordero',
      'Darkelis Cardozo',
      'Daanubi Guerra',
      'Ashley Valentina Pacheco',
      'Nazareth Ramírez',
      'Jeiner Narvaez',
      'Dixon Ramírez',
      'Eva Colón',
      'Sebastián Bastida',
      'Danexy Izquiel',
      'Samuel Rodríguez',
      'Eskleidy Montesino',
      'Reniel Toledo',
      'Diana Pacheco',
      'Sair Cordero',
    ],
    sectionGrade: '3',
  },
  {
    sectionName: '4to Grado, sección: A',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Valeria  Abreu',
      'Cristian Acosta ',
      'Mahatma Blanco ',
      'Omar Cabeza',
      'Daylith Campos ',
      'Adrian  Castrillo',
      'Marianyely Cedeño ',
      'Cristberlin Cedeño',
      'Camila Coronado',
      'Karelis Duran',
      'Jose Flores ',
      'Dianneli Gonzalez ',
      'Estefania Gonzalez ',
      'Deivis Gutiérrez ',
      'Yoiber Mendoza ',
      'Albert Muria',
      'Dalysmel Ortiz',
      'Aaron Peralta',
      'Angel  Rivero',
      'Saviel Rodiguez',
      'Yulienny Rodríguez ',
      'Sebastian Suarez',
      'Nicol Zuñiga',
      'Yenis Vargas ',
      'Iriannys Urbina',
      'Marielis Atuñez',
      'Lucely Loaiza',
    ],
    sectionGrade: '4',
  },
  {
    sectionName: '4to Grado, sección: B',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Luciana Perry',
      'Ariannys Fumero',
      'Ariannys Guerra',
      'Jhoiner Ache',
      'Ezequiel Moncada',
      'Susej Mendez',
      'Mariangel Gómez',
      'Fernando Ramírez',
      'Jiorgelis Rodríguez',
      'Carwin Castillo',
      'Jarelys Sabala',
      'Marianny Jiménez',
      'Diliyer Flores',
      'Rachelle Hernández',
      'Aslhey Ruíz',
      'Abraham Martínez',
      'Harviet Delgado',
      'Kristian Lizarraga',
      'Sebastián Álvarez',
      'Albanis Duran',
      'Dana Ron',
      'Santiago Rosales',
      'Lucely Loviza',
      'José Gutiérrez',
      'Luciana  Perry',
      'Georgelis Avendaño',
      'Fernando Ramírez',
    ],
    sectionGrade: '4',
  },
  {
    sectionName: '5to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Amada  Ramírez',
      'Scarlet Piñango',
      'Cristian Guaregua',
      'Luis  Astor',
      'Valeria Lombardi',
      'Moisés Soto',
      'Esael Ramos',
      'Samuel Romero',
      'Darwinson Belisario',
      'Dixon Pacheco',
      'Sebastian Navas',
      'Erick Salazar',
    ],
    sectionGrade: '5',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
  {
    sectionName: '6to Grado, sección: U',
    sectionImg:
      '../../../../../assets/images/pdf/yearbook/logo_partner_test.jpeg',
    sectionStudents: [
      'Yaslevis González',
      'Willians Tribiño',
      'Stefany Hernández',
      'Isai Vega',
      'Danielys Escobar',
      'Sebastian Maldonado',
      'Pablo Osal',
      'Ronuliz Alfonso',
      'Camila Ramírez',
      'Moises Salas',
      'Eglve Jiménez',
      'Sebastián Mendoza',
      'Diego Maldonado',
      'Santiago Navas',
      'Josué Arvelo',
      'Gabriel Rivero',
      'Krismar Camejo',
      'Christian Plaza',
      'Gabriel Seducia',
      'Franyer Rondon',
      'Ángel Zambrano',
      'Julian Castillo',
      'Franyelys Castillo',
      'Denyer Aular',
      'Anailyn Duran',
      'Javier Zamora',
      'Kimberly Lizarraga',
      'Dariagnis Granado',
      'Oscar Herrera',
      'Egleanny Gutiérrez',
      'Samuel Guedez',
      'Ismel Herrera',
      'Estefany Gómez',
      'Jhosverth Maestre',
      'María Contreras',
      'Franyely Chuello',
    ],
    sectionGrade: '6',
  },
]
