export * from './Template';
export * from './Pager';
export * from './ActivityTemplate';
export * from './FrontPageTemplate';
export * from './schoolGradesTemplate';
export * from './SecondLayoutTemplate';
export * from './/DiagnosticTemplate';
export * from './IndexTemplate';
export * from './GalleryTemplate';
