export * from './Template';
export * from './Pager';
export * from './ActivitiesPage';
export * from './frontPage';
export * from './schoolGradesTemplate';
export * from './TemplateThird';
export * from './SecondLayoutTemplate';
export * from './/DiagnosticTemplate';
export * from './IndexTemplate';
